### ISSUE TITLE
Error: Method may only be called on a Type for which Type.IsGenericParameter is true.

### ISSUE THREAD

**Issue by syaifulnizamyahya** [thomasgalliker/ObjectDumper#1]
I have been getting this error message when dumping DirectoryEntry object.

Message = "Method may only be called on a Type for which Type.IsGenericParameter is true."

This is how I called it.

                string test = ObjectDumper.Dump(directoryEntry);

Any advice?

**Comment by thomasgalliker** [comment]
I tried to dump a simple DirectoryEntry to WinNT localhost. The problem is that DirectoryEntry is a huge object with lots of COM imported properties. I'm not superfamiliar with DirectoryEntry but it looks like a pretty complex thing. I added some exception handling in the latest 1.0.2-prerelease but I could definitely not dump the DirectoryEntry object. Maybe you want to give it a try? Create a github fork of this repository, add a unit test in ObjectDumperTests and try to reproduce the error. Once you're done, you can create a pull request (or message me if you need help with this). Okay?

**Comment by thomasgalliker** [comment]
Could you try the latest pre-release an verify if this issue still exists, syaifulnizamyahya?

**Comment by thomasgalliker** [comment]
Could you try the latest pre-release an verify if this issue still exists, syaifulnizamyahya?
