### ISSUE TITLE
Add DumpIgnoreAttribute(); exclude properties with accessor "protected internal"

### ISSUE THREAD

**Issue by ewmccarty** [thomasgalliker/ObjectDumper#2]
Currently ObjectDumper is dumping properties which have accessor "protected internal" 

        [Newtonsoft.Json.JsonIgnore()]
        protected internal NLog.Logger Log { get; private set; }

Might be nice to have an Attribute similar to JsonIgnore();

**Comment by thomasgalliker** [comment]
I was thinking of this too. I think we should also (generally) not dump streams.

**Comment by thomasgalliker** [comment]
Check out the latest nuget release (https://www.nuget.org/packages/ObjectDumper.NET). I tried to avoid an attribute because you would create a dependency from your classes to the object dumper which is probably not what you want.

The dumper now offers optional DumpOptions to be passed. Check them out. There is one property „ExcludeProperties“ which ignores the defines property names. 

Let me know if this helps you.

**Comment by granadacoder** [comment]
ExcludeProperties is appreciated (over adding one more car to the dependency train).  Thanks.
