### ISSUE TITLE
dumping an object with recursive references

### ISSUE THREAD

**Issue by windump** [thomasgalliker/ObjectDumper#55]
seems impossible right now to dump an object with recursive references

would you accept a patch for this ?

**Comment by thomasgalliker** [comment]
I think the console dumper has some object tracking to avoid recursion? We might also want that in the CSharpDumper. As a workaround, you use Dump(obj, withOptions) where you set the MaxLevel option to any positive number. 

Contributions are welcome. I just look over it and want to keep the code style and quality level.

**Comment by thomasgalliker** [comment]
@windump  have a look at PR #53. Do you think this could solve the problem of nested/recurring references?

**Comment by thomasgalliker** [comment]
Further improvement is done for recursive objects. Objects are now being tracked so that infinite loops (which cause the StackOverflowException) should no longer happen. The latest pre-release of this nuget package contains this change. I'm always happy for feedback 💯 

https://www.nuget.org/packages/ObjectDumper.NET/2.5.20143.3-pre  (and newer)
